btrfs-tools:Fix multithreaded building
Fixes bug: [YOCTO #1524]

Fixes this error with make -j:
btrfsctl.c
| i586-poky-linux-gcc  -m32   -march=i586
--sysroot=/intel/poky/builds/world/tmp/sysroots/qemux86
-Wp,-MMD,./.btrfsctl.o.d,-MT,btrfsctl.o -Wall -D_FILE_OFFSET_BITS=64
-D_FORTIFY_SOURCE=2 -O2 -pipe -g -feliminate-unused-debug-types -c
btrfsctl.c
| btrfsctl.c:37:21: fatal error: version.h: No such file or directory
| compilation terminated.
| btrfslabel.c:40:21: fatal error: version.h: No such file or directory
| compilation terminated.

(From OE-Core rev: 3ebc06c2f011da95fd6bed74c9e27b2148011ee7)

Signed-off-by: Nitin A Kamble <nitin.a.kamble@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>