qtbase: move virtual/libgl dependency to extra variable
* makes it easier to change desktop gl to gles2 in .bbappend

* we cannot explicitly disable opengl with -no-opengl, because then it
  fails to build (probably only when mesa headers are found in sysroot)
  /qtbase-opensource-src-5.0.0/src/platformsupport/eglconvenience/qeglplatformcontext.cpp:62:72: error: 'QPlatformOpenGLContext' has not been declared
  /qtbase-opensource-src-5.0.0/src/platformsupport/eglconvenience/qeglplatformcontext.cpp: In constructor 'QEGLPlatformContext::QEGLPlatformContext(const QSurfaceFormat&, int*, EGLDisplay, EGLenum)':
  /qtbase-opensource-src-5.0.0/src/platformsupport/eglconvenience/qeglplatformcontext.cpp:69:70: error: invalid static_cast from type 'int*' to type 'QEGLPlatformContext*'
  The same with 5.0.2

(From meta-qt5 rev: 94b2064593e565ceaefdd7ef32506a99b0e6792b)

Signed-off-by: Simon Busch <morphis@gravedo.de>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>