gcc: Fix fail to compile since they can't find limits.h include.
With gcc package on my build machine gcc can't find limits.h include.

$ cat x.c

$ gcc -M x.c
In file included from x.c:1:
/usr/include/limits.h:125:26: error: no include path in which to search for limits.h

This patch adds missing includes to gcc package.

Signed-off-by: Enric Balletbo i Serra <eballetbo@iseebcn.com>
Signed-off-by: Richard Purdie <rpurdie@linux.intel.com>