qtwayland: Add xproto dependency together with libxkbcommon
* xproto provides X11/keysym.h which is used when testing libxkbcommon support:
executing config test xkbcommon
+ cd /OE/work/i586-oe-linux/qtwayland/5.1.0+git/build/config.tests/xkbcommon && /OE/sysroots/x86_64-linux/usr/bin/qt5/qmake "CONFIG -= qt debug_and_release app_bundle lib_bundle" /OE/work/i586-oe-linux/qtwayland/5.1.0+git/git/config.tests/xkbcommon
+ cd /OE/work/i586-oe-linux/qtwayland/5.1.0+git/build/config.tests/xkbcommon && make      MAKEFLAGS='-j 9'     OE_QMAKE_COMPILER='i586-oe-linux-gcc  -m32 -march=i586 --sysroot=/OE/sysroots/qemux86'     OE_QMAKE_CC='i586-oe-linux-gcc  -m32 -march=i586 --sysroot=/OE/sysroots/qemux86'     OE_QMAKE_CXX='i586-oe-linux-g++  -m32 -march=i586 --sysroot=/OE/sysroots/qemux86'     OE_QMAKE_CFLAGS=' -O2 -pipe -g -feliminate-unused-debug-types'     OE_QMAKE_CXXFLAGS=' -O2 -pipe -g -feliminate-unused-debug-types -fpermissive -fvisibility-inlines-hidden'     OE_QMAKE_LINK='i586-oe-linux-g++  -m32 -march=i586 --sysroot=/OE/sysroots/qemux86'     OE_QMAKE_LDFLAGS='-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed'     OE_QMAKE_AR='i586-oe-linux-ar'     OE_QMAKE_STRIP='echo'     OE_QMAKE_WAYLAND_SCANNER='/OE/sysroots/x86_64-linux/usr/bin/wayland-scanner'
compiling /OE/work/i586-oe-linux/qtwayland/5.1.0+git/git/config.tests/xkbcommon/main.cpp
/OE/work/i586-oe-linux/qtwayland/5.1.0+git/git/config.tests/xkbcommon/main.cpp:42:24: fatal error: X11/keysym.h: No such file or directory
compilation terminated.
make: *** [.obj/release-shared/main.o] Error 1
test xkbcommon FAILED

(From meta-qt5 rev: 886509518d5662e42b1177c88403ebb31454c605)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>