inetutils: add -dbg packages for tftpd, telnetd and rshd
The packages tftpd, telnetd and rshd conflict with the ones
provided by netkit, so add the corresponding -dbg packages
for them to avoid the following confliction between the dbg
package of inetutils and netkit:

error: file /usr/sbin/.debug/in.rexecd conflicts between attempted installs of inetutils-dbg-1.9.1-r1.0.armv7a_vfp_neon and netkit-rsh-dbg-0.17-r0.0.armv7a_vfp_neon
error: file /usr/sbin/.debug/in.telnetd conflicts between attempted installs of inetutils-dbg-1.9.1-r1.0.armv7a_vfp_neon and netkit-telnet-dbg-0.17-r0.0.armv7a_vfp_neon

(From meta-openembedded rev: bc969d3705c45928de8525ef3d2d9d2867311864)

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Joe MacDonald <joe@deserted.net>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>