media-ctl: Use linux-libc-headers instead of linux kernel sources
Use the headers from the linux-libc-headers instead of the headers
from the linux kernel sources because user space programs should
be built against the header files provided by the distribution.

In file included from .../usr/src/kernel/include/linux/media.h:27:0,
                 from conftest.c:56:
.../usr/src/kernel/include/linux/types.h:13:2: warning: #warning \
"Attempt to use kernel headers from user space, see http://kernelnewbies.org/KernelHeaders" [-Wcpp]

On some platforms (qemu) intern kernel header (linux/types.h) redefines
some types from the system header (sys/types.h, timer.h, stdint.h)
and thereby breaks the checking of the linux media header.

ERROR: Kernel header file not found or not usable!

In file included from .../usr/include/linux/media.h:27:0,
                 from conftest.c:56:
In file included from .../usr/src/kernel/include/linux/types.h:14:26: error: conflicting types for 'fd_set'
In file included from .../sys/select.h:75:5: note: previous declaration of 'fd_set' was here

Similar errors for dev_t, mode_t, timer_t, uintptr_t and blkcnt_t.

(From meta-openembedded rev: 0c47dcf1dfe9cb5fb2fbe06e06d42920c6f4bcc0)

Signed-off-by: Stefan Herbrechtsmeier <stefan@herbrechtsmeier.net>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>