rrdtool: Remove hard-coded include in configure.ac
Got an error building rrdtool because of hard-coded paths in the
configure.ac file. The extact error message was:

ERROR: This autoconf log indicates errors, it looked at host include and/or library paths while determining system capabilities.
Rerun configure task after fixing this. The path was '/home/marc/yoctomaster/build/crownbay/tmp/work/core2-poky-linux/rrdtool-1.4.7-r2/rrdtool-1.4.7'

(From meta-openembedded rev: 946c52ccf1cbdaa1d6337486e9ac3a1b0f3bb8a5)

Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>