rrdtool: add PACKAGECONFIG for dbi
* dbi was autodetected from sysroot causing undeterministic builds and failures
  in lmsensors builds:
  ld: warning: libdbi.so.1, needed by sysroots/qemux86/usr/lib/librrd.so,
  not found (try using -rpath or -rpath-link)
  sysroots/qemux86/usr/lib/librrd.so: undefined reference to `dbi_result_get_string_idx'

(From meta-openembedded rev: db4e0caccab0b5bc1bc59307d6289e8bf9793bc9)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>