azy: simplify do_configure
* probably because of
  http://git.openembedded.org/bitbake/commit/?id=9fc98f96f0e0320beda0ce9546275a99336732c1
  it now failed with
  /OE/jansa-test/shr-core/tmp-eglibc/work/x86_64-linux/azy-native/2_1.0.0+svnr80969-r0/temp/run.do_configure.30731: line 88: efl_do_configure: command not found
  ERROR: Function failed: do_configure (see /OE/jansa-test/shr-core/tmp-eglibc/work/x86_64-linux/azy-native/2_1.0.0+svnr80969-r0/temp/log.do_configure.30731 for further information)

(From meta-openembedded rev: 833d36faf08ab08a1715e4a3094994aba8a2bd39)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>