devilspie2: update to 0.33
Note: 0.24 failed if lua >= 5.2 was build before devilspie (e.g world build) with

| src/script.c: In function 'init_script':
| src/script.c:65:2: warning: implicit declaration of function 'lua_open' [-Wimplicit-function-declaration]
|   lua_State *lua=lua_open();
|   ^
| src/script.c:65:17: warning: initialization makes pointer from integer without a cast [enabled by default]
|   lua_State *lua=lua_open();
|                  ^
| arm-angstrom-linux-gnueabi-gcc  -march=armv7-a -mthumb -mthumb-interwork -mfloat-abi=hard -mfpu=neon --sysroot=/home/superandy/tmp/oe-core-eglibc/sysroots/overo -ldl -lm -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  obj/devilspie2.o obj/xutils.o obj/script.o obj/script_functions.o -o bin/devilspie2 -lX11 `pkg-config --libs gtk+-2.0 libwnck-1.0 lua5.1`
| src/script.c:65: error: undefined reference to 'lua_open'

(From meta-openembedded rev: 49135be237314503a2b93fdf92ad10088e7859e9)

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>