recipes-git: Upgrade to latest origin/stable
* qtbase: Fix undefined reference to qt_blend_argb32_on_argb32_ssse3

(From meta-qt5 rev: cf2c7816fd053ff16a41abdc6f2a89fe9ff7a7ff)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>