curlpp: fix do_compile failed since gcc upgrade to 4.9
The deprecated test code was no longer used, so remove it
to avoid compiling failure with -Werror=unused-function
...
| example21.cpp:51:8: error: 'size_t {anonymous}::readData(char*,
size_t, size_t)' defined but not used [-Werror=unused-function]
|  size_t readData(char *buffer, size_t size, size_t nitems)
...

(From meta-openembedded rev: 8afe9200c45110eb2166e09bdce739fa170c08cb)

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>