libdvdread: update to version 4.2.0
The previous version (4.1.3-10) was unbuildable due to this issue:

WARNING: Failed to fetch URL git://git.debian-maintainers.org/git/daniel/libdvdread.git;protocol=git;branch=debian,
   attempting MIRRORS if available
ERROR: Fetcher failure: Fetch command failed with exit code 128, output:
Cloning into bare repository <snip>/downloads//git2/git.debian-maintainers.org.git.daniel.libdvdread.git...

fatal: Unable to look up git.debian-maintainers.org (port 9418) (Name or service not known)

(From meta-openembedded rev: 4f2ae6f5bdd14bf56ae115f8fce16674af3e04bd)

Signed-off-by: Mario Domenech Goulart <mario@ossystems.com.br>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>