mozjs: Fix QA errors when building with multilib
We do not take care of default libdir which accidently
works out to be ok for non-multilib case since its /usr/lib

Fixes error like

ERROR: QA Issue: mozjs: Files/directories were installed but not shipped
  /usr/lib
  /usr/lib/libmozjs-17.0.a
  /usr/lib/libmozjs-17.0.so
  /usr/lib/pkgconfig
  /usr/lib/.debug
  /usr/lib/pkgconfig/mozjs-17.0.pc
  /usr/lib/.debug/libmozjs-17.0.so

(From meta-openembedded rev: eed618223062e69466d3b64ff27ded342c498d83)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Acked-by: Koen Kooi <koen@dominion.thruhere.net>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>