pango: upgrade to 1.29.4
* pango older than 1.29.1 causes ie libglade build fail with
  /usr/include/pango-1.0/pango/pango-script.h:132:12: error: unknown type name 'G_CONST_RETURN'

(From meta-openembedded rev: f6b6238d617b70d2222b5cdea2db3d375bc5549d)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>