avahi: fix configure with automake 1.11.2
automake version 1.11.2 has made use of dir variables more strict.
use of pkglibdir with DATA var results in automake errors.
  This commits uses pkgdatadir var instead of pkglibdir to avoid
the strict check errors.

Fixes this error:
service-type-database/Makefile.am:21: `pkglibdir' is not a legitimate
directory for `DATA'
autoreconf: automake failed with exit status: 1
ERROR: autoreconf execution failed.

(From OE-Core rev: ea7e61c14f7fcf917ea1cf4811e5cceb5003a030)

Signed-off-by: Nitin A Kamble <nitin.a.kamble@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>