ptpd-2.2.0: drop the patch adjust-daemon-name.patch
The patch adjust-daemon-name.patch is to change the daemon name
ptpd2 back to ptpd, which broke some functionality:

root@qemu0:~# ptpd -g
Error: 1 ptpd daemon(s) detected in parallel, but we were not expecting any. Exiting.

so drop it and use the default daemon name ptpd2.

(From meta-openembedded rev: 5955e22f6ecf0196a129c27641c6d85820f8b962)

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>