netcat-openbsd: Update to 1.105
Add the missing dependency on libbsd
it was not building otherwise. libbsd recipes for OE-Core
has been ported please wait until they are applied

| netcat.c:99:24: fatal error: bsd/stdlib.h: No such file or directory
|  #include <bsd/stdlib.h>
|                         ^
| compilation terminated.
| make: *** [netcat.o] Error 1
| make: *** Waiting for unfinished jobs....
| socks.c:41:32: fatal error: bsd/readpassphrase.h: No such file or directory
|  #include <bsd/readpassphrase.h>

(From meta-openembedded rev: 17bd75d60f42bfe3a10f299ace5432e2c97037d4)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Joe MacDonald <joe.macdonald@windriver.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>