ser2net: change file used in LIC_FILES_CHKSUM
* INSTALL file is automatically created by automake (now when it doesn't have
  implicit foreign) and it changed the md5 to d0697e131465c2bdd0af3b07a84d2878
  causing do_configure task to fail with:

  ERROR: ser2net: md5 data is not matching for file://INSTALL;md5=0659eb117294c490ae3853facd7a6ddd
  ERROR: ser2net: The new md5 checksum is d0697e131465c2bdd0af3b07a84d2878

  Use COPYING file which should be more stable.

* adding foreing automake flag is maybe more correct solution, I wonder
  how many projects were changed like this, but silently (this failed
  only thanks to INSTALL file being used in LIC_FILES_CHKSUM)

(From meta-openembedded rev: e49e5d601af97afd026cad424065f678c47d2cc1)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>