e-base: bump EFL_SRCREV remove EFL_SRCREV_1.* and applied patches from libeflvala, elsa and python-elementary
* elementary (Evas_GL) and e-wm (backlight) depends on trunk again..

10:06:36 < JaMa> shouldn't elementary and e17 depend only on efl-1.1? | ./Elementary.h:372:21: fatal error: Evas_GL.h: No such file or directory and e/src/bin/e_backlight.c:43: undefined reference to
                 `ecore_x_randr_output_backlight_available'
10:07:32 < JaMa> but I'll recheck my configs
10:08:20 < moa> hum, that evas_gl.h would be a problem indeed
10:08:36 < moa> for e, i don't know
10:08:57 <@raster> elm requires svn evas
10:09:02 <@raster> thats unfortunately how it is
10:09:12 <@raster> requires evas_gl
10:09:35 < JaMa> maybe this is missing in 1.1 branch for e17? r65838
10:09:42 <@raster> yes
10:09:46 <@raster> its missing
10:09:50 <@raster> as its in trunk
10:09:53 <@raster> its a "new feature"
10:09:58 <@raster> not in stable
10:10:15 <@raster> uy'd have to patch out the support to make elm from svn build
10:10:42 < JaMa> raster: ok then I just didn't understand the dependency on "only" efl-1.1 right.. I'll update the rest of efl to same rev (instead of keeping them on 1.1 release)

(From meta-openembedded rev: 458f724d9bdb716b6907ea797a92fe0f67f1f72b)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>