gtkperf: add gtk+ dependency
* when there is no gtk+ in sysroot, configure fails to find it
  but doesn't cause do_configure task to fail :/

  configure: WARNING: using cross tools not prefixed with host triplet
  checking pkg-config is at least version 0.9.0... yes
  checking for GTK... no

* builds fails a bit later with confusing do_install error:
  ERROR: Function failed: do_install (log file is located at /OE/build/oe-core/tmp-eglibc/work/i586-oe-linux/gtkperf/0.40-r0/temp/log.do_install.31526)
  ERROR: Logfile of failure stored in: /OE/build/oe-core/tmp-eglibc/work/i586-oe-linux/gtkperf/0.40-r0/temp/log.do_install.31526
  Log data follows:
  | DEBUG: SITE files ['endian-little', 'bit-32', 'ix86-common', 'common-linux', 'common-glibc', 'i586-linux', 'common']
  | DEBUG: Executing shell function do_install
  | NOTE: make -j 9 DESTDIR=/OE/build/oe-core/tmp-eglibc/work/i586-oe-linux/gtkperf/0.40-r0/image install
  | make: *** No rule to make target 'install'.  Stop.
  | ERROR: oe_runmake failed
  | WARNING: /OE/build/oe-core/tmp-eglibc/work/i586-oe-linux/gtkperf/0.40-r0/temp/run.do_install.31526:1 exit 1 from
  |   exit 1
  | ERROR: Function failed: do_install (log file is located at /OE/build/oe-core/tmp-eglibc/work/i586-oe-linux/gtkperf/0.40-r0/temp/log.do_install.31526)
  NOTE: recipe gtkperf-0.40-r0: task do_install: Failed
  ERROR: Task 2 (/OE/build/oe-core/meta-openembedded/meta-oe/recipes-graphics/gtkperf/gtkperf_0.40.bb, do_install) failed with exit code '1'

(From meta-openembedded rev: 2c313ca01f12b333f1f7ed224627566fbfca336f)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>