qtbase: xinput2 depends on libxi
| ../../../../qtbase-opensource-src-5.2.1/config.tests/x11/xinput2/xinput2.cpp:43:36: fatal error: X11/extensions/XInput2.h: No such file or directory
|  #include <X11/extensions/XInput2.h>
|                                     ^
| compilation terminated.
| make: *** [xinput2.o] Error 1
| XInput2 disabled.
| XInput2 support cannot be enabled due to functionality tests!

(From meta-qt5 rev: 6b1ad9ef455e048802f41b5d446cc3ac9c3bdfb6)

Signed-off-by: Andreas Oberritter <obi@opendreambox.org>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>